# Generated by Django 5.2.6 on 2025-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_station',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_station_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_station_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_station_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
